refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  server:
    kind: file
    path: "logs/server.log"
    encoder:
      pattern: "{d} [{l:>5}][{t}] {m}{n}"
  client:
    kind: file
    path: "logs/client.log"
    encoder:
      pattern: "{d} [{l:>5}][{t}] {m}{n}"
root:
  level: trace
  appenders:
    - server
loggers:
  server:
    level: trace
    appenders:
      - server
  client:
    level: trace
    appenders:
      - client
